### PR TITLE
Change API url for /api/compliance/scap_contents

### PR DESCRIPTION
**Pull request by isimluk**
Relates to #89.

I will move other arf controller later on.

### CODE REVIEW

**Comment by isimluk** [comment]
all migrated. I will just retest the backend.

**Comment by shlomizadok** [comment]
needs to be amended with https://github.com/OpenSCAP/foreman_openscap/commit/f6c0fdf715ff6d2e264817add4490e0e19f272cd and ready to merge :+1:

**Comment by isimluk** [comment]
Actually, we have got lucky. There is not conflict! The f6c0fdf goes to a line that was not touched by this pr.

**Comment by isimluk** [comment]
Merged!

**Pull request closed without merging**
